// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt time.Time
}

type Entry struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Amount    int64
	CreatedAt time.Time
}

type Transfer struct {
	ID            uuid.UUID
	FromAccountID uuid.UUID
	ToAccountID   uuid.UUID
	Amount        int64
	CreatedAt     time.Time
}

type User struct {
	Username         string
	HashedPassword   string
	FullName         string
	Email            string
	PasswordChangeAt time.Time
	CreateAt         time.Time
}
