// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfers(ctx context.Context, arg CreateTransfersParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// In commonly UPDATE will lock the database but still allow other transaction to query the data
	// So we can use it directly instead of use SELECT ... FOR UPDATE and then UPDATE
	DeleteAccount(ctx context.Context, id uuid.UUID) error
	DeleteEntry(ctx context.Context, id uuid.UUID) error
	DeleteTransfers(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, username string) error
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountForUpdate(ctx context.Context, id uuid.UUID) (Account, error)
	GetEntry(ctx context.Context, id uuid.UUID) (Entry, error)
	GetTransfers(ctx context.Context, id uuid.UUID) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	// Lock Database but still allow other transaction to query the data
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) error
	UpdateTransfers(ctx context.Context, arg UpdateTransfersParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
